# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-15 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
